### ISSUE TITLE
Custom memory allocation implementation?

### ISSUE THREAD

**Issue by orestisfl** [Jacarte/wakoko_instrumentor#2]
I noticed you implemented some malloc/free wrappers in https://github.com/Jacarte/wakoko_instrumentor/blob/main/lib/utils/utils.c but I don't see their usefulness. In the end, you are still leaking memory since you never free what you allocate and you use stdlib calls inside the wrappers.

Besides, I don't understand the need for `MAX_ALLOCATIONS`.

**Comment by Jacarte** [comment]
Well, that's true, so, my point here is since the main target is WASM, I am pretty sure the browser engine frees the resources How do you propose to fix it?

**Comment by orestisfl** [comment]
I don't think that the browser will free memory while you are using it (from it's point of view this should be random parts of the linear memory, it doesn't know if your program is still using them). You should either 1. free memory after you are done using it 2. accept that your program will leak memory throughout it's use and ignore the problem.

**Comment by Jacarte** [comment]
Well...in the browser the application executes only one time, so I would say option 2. However, if you plan to use it natively option 1 should be important.

**Comment by orestisfl** [comment]
What's the difference? Will the application be running continuously on native?
